### ISSUE TITLE
Create Github App User for automatic updates.

### ISSUE THREAD

**Issue by stacksjb** [tod-org/tod#1326]
Currently release-please and similar tasks for Github CI are using a Personal Access Token (PAT).

This works well, but has some caveats:
- All actions/tasks (such as new release, build, etc) show as being tied to the user instead of the actor
- Branch restrictions apply (unless bypassed for the user)

By creating an org "App" these rules can be tied to the app instead of the individual user

see https://github.com/peter-murray/workflow-application-token-action 

Once created, the tokens can be stored as a Github Secret and then CI actions can be replaced to use those.

**Comment by stacksjb** [comment]
An alternative (older method) would be to use a deploy key, but the newer method is to set up an app which would be preferred.

Then the CI steps would be updated to look something like this:

```
- name: Generate GitHub App token
  id: app-token
  uses: peter-murray/workflow-application-token-action@v3
  with:
    application_id: ${{ secrets.APP_ID }}
    application_private_key: ${{ secrets.APP_PRIVATE_KEY }}

- name: Push manifest update via App
  env:
    GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
  run: |
    git config user.name "release-bot"
    git config user.email "bot@example.com"
    git checkout main
    git pull
    # apply changes...
```
